### PR TITLE
Updated Ow_dom.any_elt' type with Main tag.

### PR DESCRIPTION
**Pull request by sagotch**
Tyxml has been updated with the same tag. This patch restore type compatibility.

### CODE REVIEW

**Comment by Drup** [comment]
First time I see this piece of code ... you should rather include tyxml's type directly.

**Comment by sagotch** [comment]
Maybe... but I have no idea about what this type is for.

Introduced by @ccharly with https://github.com/ocsigen/ocsigen-widgets/commit/9a8024c075b951684a51400d36f0b753718051ac (any hint?)

**Comment by Drup** [comment]
It seems to be used by some `dyn_alert` things, but I don't know why. `'a` should be enough in those places, and there are no comments.

**Comment by ccharly** [comment]
hey there, it's been a while now I've used ocsigen, so I cannot recall myself why I did add this type, maybe because it was not possible to use shared variable with polymorphic types? Widgets were intended to be used in both sides. Using this type was making possible to use any html elements with those kind of variables.

Thus said, I don't really remember if this is the only reason. Anyway, this may help you a bit (maybe ;))

**Comment by vasilisp** [comment]
The disparity with respect to `main` breaks EBA, and @sagotch's branch fixes it back.

If `any_elt'` was indeed a workaround for the Eliom polymorphism restrictions (which seems very plausible), we can instead use conversions to/from XML ("untyped") elements in the few places needed. This is ugly, but no more so than maintaining an `any` variant.

In general, naming arbitrary collections of TyXML tags outside TyXML is bound to cause trouble, because TyXML makes no promise of "not adding" stuff.

**Comment by vasilisp** [comment]
I removed `Ow_dom` (b56dcf4), sprinkled in some type variables, and everything seems to be fine.

We get some more warnings, but hiding them under the carpet with `any_elt'` is not the solution.

@ccharly, could you take a look and tell me if the new types capture your intentions?

**Comment by ccharly** [comment]
LGTM. :)

**Pull request closed without merging**
